# Site settings
title: CAES web dev
email: cydoval@ucdavis.edu
description: > # this means to ignore newlines until "baseurl:"
  Current projects for the web team at UC Davis College of Agricultural and Environmental Sciences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webdev-caes.ucdavis.edu" # the base hostname & protocol for your site
twitter_username: cydoval
github_username:  cydoval

# Build settings
markdown: kramdown
